include: package:flutter_lints/flutter.yaml
linter:

  rules:

    prefer_single_quotes: true
    avoid_print: true
    empty_statements: true
    prefer_relative_imports: true
    unnecessary_statements: true
    avoid_unnecessary_containers: true
    constant_identifier_names: true
    file_names: true
    require_trailing_commas: true
    avoid_function_literals_in_foreach_calls: false

